safe: true

title: Lolita Godefroy - Psychologue Énergéticienne
email: lolita.godefroy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "Psychothérapie et Soins Reiki pour adultes, adolescents et enfant sur Toulouse." 
image_to_share: https://res.cloudinary.com/dytqwkbym/image/upload/v1568560954/arbres_cf1pov.jpg

organization: Lolita Godefroy

author: Haythem OUEDERNI

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: todo

# Lolita on social medias
social_links:
  facebook: https://www.facebook.com/L%C3%89veil-de-l%C3%A2me-1549365928526980/
  twitter: todo
  instagram: https://www.instagram.com/lolita_therapeute/



# facebook information
facebook_app_id: todo

# Build settings
google_analytics_id: UA-83975665-2
google_site_verification: WIKSY2Wl0zz8RzDPN8tdIOB9MMZ_1fcoUu3wJhzAAl0


lolita_godefroy_website: https://lolita-godefroy-psychologue.github.io/

timezone: Europe/Paris

markdown: kramdown
#theme: minima

highlighter: rouge

gems:
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - README.md

sass:
  sass_dir: _sass
  style: compressed

defaults:
  -
    scope:
      path: "" # for the file on the root
    values:
      layout: "default"
  -
    scope:
      path: "_docs"
    values:
      layout: "default"
  -
    scope:
      path: "pages"
    values:
      layout: "default"
